### ISSUE TITLE
Why do you use react 17.0.2?

### ISSUE THREAD

**Issue by yborisovp** [imshafikul/react-shimmer-effects#2]
I think this package would be more popular if you lowered the react version to ^16

**Comment by shafikulz** [comment]
@Losur  Thanks for the feedback. Will fix and let you know asap.

**Comment by abuamr-gafurov** [comment]
Hi.
Also don't support react 18

**Comment by Raheelanwar-gfl** [comment]
npm ERR! 404
npm ERR! 404  '@types/react-shimmer-effects-18@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rahee\AppData\Local\npm-cache\_logs\2023-03-10T06_54_28_303Z-debug-0.log

**Comment by PayalSasmal10** [comment]
Still the issue not resolved


npm ERR! 
npm ERR! While resolving: tv-series-tracker@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from react-shimmer-effects@1.0.2
npm ERR! node_modules/react-shimmer-effects
npm ERR!   react-shimmer-effects@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/payal/.npm/_logs/2023-10-11T05_41_30_477Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/payal/.npm/_logs/2023-10-11T05_41_30_477Z-debug-0.log

**Comment by imshafikul** [comment]
@abuamr-gafurov @PayalSasmal10 @yborisovp @Raheelanwar-gfl 
Issue fixed.
Sorry for late

Thanks
