### ISSUE TITLE
Please update the React version 

### ISSUE THREAD

**Issue by hrishiranjan** [imshafikul/react-shimmer-effects#6]
Its creating issues while downloading from npm

**Comment by imshafikul** [comment]
@hrishiranjan thanks for raising it
Can you please explain what problem you are facing?

**Comment by hrishiranjan** [comment]
While installing through npm.. it throws err for peer dependency of react@17.
We have to  force install to use the package

**Comment by imshafikul** [comment]
@hrishiranjan fixed this issue. 
Sorry for the late.
Thanks

**Comment by hrishiranjan** [comment]
Thanks :)
